//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.IValidationService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.IValidationService.SampleFiles", typeof(SampleFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt; 
        ///&lt;catalog xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot; xmlns:xcri=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:credit=&quot;http://purl.org/net/cm&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot; xmlns:x=&quot;http://www.w3.org/1999/xhtml&quot;  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog http://www.xcri.co.uk/bindings/xcri_cap_1_2.xsd http://xcri.org/profiles/1.2/catalog/terms h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthLindseyCollege_20120223 {
            get {
                return ResourceManager.GetString("NorthLindseyCollege_20120223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot; xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot; xmlns:credit=&quot;http://purl.org/net/cm&quot; xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot; xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog http://www.xcri.co.uk/bindings/xcri_cap_1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UniversityOfCentralLancaster_20120228 {
            get {
                return ResourceManager.GetString("UniversityOfCentralLancaster_20120228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;catalog
        ///xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot;
        ///xmlns:xcriTerms=&quot;http://xcri.org/profiles/catalog/terms&quot;
        ///xmlns:credit=&quot;http://purl.org/net/cm&quot;
        ///xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; 
        ///xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot;
        ///xmlns:courseDataProgramme=&quot;http://xcri.co.uk&quot;
        ///xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///xmlns:hesa=&quot;http://www.hesa.ac.uk&quot;
        ///xmlns:xsi=&quot;http://www.w3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UniversityOfHertfordshire_20120312 {
            get {
                return ResourceManager.GetString("UniversityOfHertfordshire_20120312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;catalog xmlns:dcmitype=&quot;http://purl.org/dc/dcmitype/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:credit=&quot;http://purl.org/net/cm&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot; xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot; xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog http://www.xcri.co.uk/bindings/xcri_cap_1_2.xsd http://xcri.co.uk http://www.xcri.co.uk/bindings/courseDataProgramme.xsd http://www.w3.org/2003/01/geo/wgs84_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UniversityOfSheffield_20120406 {
            get {
                return ResourceManager.GetString("UniversityOfSheffield_20120406", resourceCulture);
            }
        }
    }
}
