//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.Vocabularies.Valid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XCRICAP12Terms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XCRICAP12Terms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.Vocabularies.Valid.XCRICAP12Terms", typeof(XCRICAP12Terms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;catalog 
        ///xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot; 
        ///xmlns:credit=&quot;http://purl.org/net/cm&quot; 
        ///xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; 
        ///xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; 
        ///xmlns:mlo=&quot;http://purl.org/net/mlo&quot; 
        ///xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot; 
        ///xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///xmlns:xcriTerms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot;
        ///xmlns:courseDataProgramme=&quot;http://xcri.co.uk&quot;
        ///xsi:schemaLocation=&quot;http://xcri.org/p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string studyHours {
            get {
                return ResourceManager.GetString("studyHours", resourceCulture);
            }
        }
    }
}
