//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.ContentValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VDEXFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VDEXFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.ContentValidation.VDEXFiles", typeof(VDEXFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vdex profileType=&quot;flatTokenTerms&quot; xmlns=&quot;http://www.imsglobal.org/xsd/imsvdex_v1p0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.imsglobal.org/xsd/imsvdex_v1p0 http://www.imsglobal.org/xsd/imsvdex_v1p0_flat.xsd&quot; xmlns:xcri=&quot;http://xcri.org/profiles/catalog&quot;&gt;
        ///
        ///&lt;vocabName&gt;
        ///
        ///	&lt;langstring&gt;Generic Study Mode for Course Data Programme.  Created by Alan Paull, APS Ltd.  This VDEX version 5 March 2012.&lt;/langstring&gt;
        ///
        ///&lt;/vocabName&gt;
        ///
        ///&lt;vocabIdentifier&gt;http://xcri.org/prof [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VDEX_020E5DC7A768E70B3481AFD9E176B7BD {
            get {
                return ResourceManager.GetString("VDEX_020E5DC7A768E70B3481AFD9E176B7BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vdex profileType=&quot;flatTokenTerms&quot; xmlns=&quot;http://www.imsglobal.org/xsd/imsvdex_v1p0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.imsglobal.org/xsd/imsvdex_v1p0 http://www.imsglobal.org/xsd/imsvdex_v1p0_flat.xsd&quot; xmlns:xcri=&quot;http://xcri.org/profiles/catalog&quot;&gt;        ///
        ///&lt;vocabName&gt;        ///
        ///	&lt;langstring&gt;Attendance Mode for Course Data Programme.  Created by Jennifer Paull, APS Ltd.  This VDEX version 5 March 2012.&lt;/langstring&gt;        ///
        ///&lt;/vocabName&gt;        ///
        ///&lt;vocabIdentifier&gt;http://xcri.org/profile [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VDEX_563DE9485AC883A619BDF882B22FEF40 {
            get {
                return ResourceManager.GetString("VDEX_563DE9485AC883A619BDF882B22FEF40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vdex profileType=&quot;flatTokenTerms&quot; xmlns=&quot;http://www.imsglobal.org/xsd/imsvdex_v1p0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.imsglobal.org/xsd/imsvdex_v1p0 http://www.imsglobal.org/xsd/imsvdex_v1p0_flat.xsd&quot; xmlns:xcri=&quot;http://xcri.org/profiles/catalog&quot;&gt;        ///
        ///&lt;vocabName&gt;        ///
        ///	&lt;langstring&gt;Attendance Pattern for Course Data Programme.  Created by Jennifer Paull, APS Ltd.  This VDEX version 5 March 2012.&lt;/langstring&gt;        ///
        ///&lt;/vocabName&gt;        ///
        ///&lt;vocabIdentifier&gt;http://xcri.org/prof [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VDEX_A1BA6F2ACE918C1C07A6454C9184FF90 {
            get {
                return ResourceManager.GetString("VDEX_A1BA6F2ACE918C1C07A6454C9184FF90", resourceCulture);
            }
        }
    }
}
