//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.ContentValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XSDFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XSDFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.ContentValidation.XSDFiles", typeof(XSDFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://purl.org/net/mlo&quot; xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        ///	xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;http://purl.org/net/mlo&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot;
        ///		schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot; /&gt;
        ///	&lt;xs:import schemaLocation=&quot;dcterms.xsd&quot; namespace=&quot;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;        ///
        ///&lt;xs:schema id=&quot;ukprn&quot;        ///
        ///    targetNamespace=&quot;http://www.ukrlp.co.uk&quot;        ///
        ///    elementFormDefault=&quot;qualified&quot;        ///
        ///    xmlns=&quot;http://www.ukrlp.co.uk&quot;        ///
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;        ///
        ///    xmlns:xcri=&quot;http://xcri.org/profiles/catalog&quot;         ///
        ///&gt;        ///
        ///  &lt;xs:import namespace=&quot;http://xcri.org/profiles/catalog&quot; schemaLocation=&quot;http://www.xcri.org/bindings/xcri_cap_1_1.xsd&quot; /&gt;        ///
        ///  &lt;xs:simpleType name=&quot;ukprn&quot;&gt;        ///
        ///    &lt;xs:restriction base=&quot;xcri:identifierDType&quot;&gt;        ///
        ///      &lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_0D62B08DE6CD9546F1095E0EECB3ECFF {
            get {
                return ResourceManager.GetString("XSD_0D62B08DE6CD9546F1095E0EECB3ECFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;        ///
        ///&lt;xs:schema xmlns=&quot;http://xcri.org/profiles/catalog/terms&quot; xmlns:x=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:xcri=&quot;http://xcri.org/profiles/catalog&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://xcri.org/profiles/catalog/terms&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/03/xml.xsd&quot;/&gt;        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_1797EA6AAD1ECCA9BAF0903A815A9C8C {
            get {
                return ResourceManager.GetString("XSD_1797EA6AAD1ECCA9BAF0903A815A9C8C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema 
        /// xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;  
        /// xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot;
        /// xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        /// elementFormDefault=&quot;qualified&quot;&gt;
        /// 
        /// 	&lt;xs:import namespace=&quot;http://www.w3.org/1999/xhtml&quot;	schemaLocation=&quot;http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd&quot; /&gt;
        /// 	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot;/&gt;
        /// 	
        /// 	&lt;!-- This schema defines some comm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_241F08195DD9A9C562036E5B3BCE60A2 {
            get {
                return ResourceManager.GetString("XSD_241F08195DD9A9C562036E5B3BCE60A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema 
        ///
        /// xmlns=&quot;http://purl.org/net/mlo&quot;
        /// xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        /// xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        /// xmlns:credit=&quot;http://purl.org/net/cm&quot;
        /// xmlns:xcri=&quot;http://xcri.org/profiles/1.2/catalog&quot;
        /// xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        /// xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        /// xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot;
        /// targetNamespace=&quot;http://purl.org/net/mlo&quot;
        ///
        /// elementFormDefault=&quot;qualified&quot;&gt;
        /// 	&lt;xs:annotation&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_2FC979F344A35B5E0A6D737E4E2C4929 {
            get {
                return ResourceManager.GetString("XSD_2FC979F344A35B5E0A6D737E4E2C4929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://purl.org/net/cm&quot;
        ///	xmlns:credit=&quot;http://purl.org/net/cm&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;annotation&gt;
        ///		&lt;documentation xml:lang=&quot;en&quot;&gt;
        ///			This is an unofficial schema for
        ///			the CEN Educational Credit Information Model (CWA 16077:2010)
        ///		&lt;/documentation&gt;
        ///	&lt;/annotation&gt;
        ///
        ///	&lt;complexType name=&quot;Credit&quot;&gt;
        ///		&lt;sequence&gt;
        ///			&lt;element ref=&quot;credit:scheme&quot; maxOccurs=&quot;1&quot; minOccurs=&quot;0&quot;/&gt;
        ///			&lt;element [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_3FFB2F8237F79943CE135AA0BB157F5C {
            get {
                return ResourceManager.GetString("XSD_3FFB2F8237F79943CE135AA0BB157F5C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://purl.org/net/mlo&quot; xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        ///	xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;http://purl.org/net/mlo&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot;
        ///		schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot; /&gt;
        ///	&lt;xs:import schemaLocation=&quot;dcterms.xsd&quot; namespace=&quot;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_57B1B1BEB0BD0365C2D534014E4C6C4E {
            get {
                return ResourceManager.GetString("XSD_57B1B1BEB0BD0365C2D534014E4C6C4E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;?xml-stylesheet href=&quot;../2008/09/xsd.xsl&quot; type=&quot;text/xsl&quot;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; 
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///  xmlns   =&quot;http://www.w3.org/1999/xhtml&quot;
        ///  xml:lang=&quot;en&quot;&gt;
        ///
        /// &lt;xs:annotation&gt;
        ///  &lt;xs:documentation&gt;
        ///   &lt;div&gt;
        ///    &lt;h1&gt;About the XML namespace&lt;/h1&gt;
        ///
        ///    &lt;div class=&quot;bodytext&quot;&gt;
        ///     &lt;p&gt;
        ///      This schema document describes the XML namespace, in a form
        ///      suitable for import by other schema documents.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_5E0BD6F94EC78A3A88FCA2275AB05F9E {
            get {
                return ResourceManager.GetString("XSD_5E0BD6F94EC78A3A88FCA2275AB05F9E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://purl.org/dc/dcmitype/&quot;
        ///           targetNamespace=&quot;http://purl.org/dc/dcmitype/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      DCMI Type Vocabulary XML Schema
        ///      XML Schema for http://purl.org/dc/dcmitype/ namespace
        ///
        ///      Created 2008-02-11
        ///
        ///      Created by 
        ///
        ///      T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_61535827A4820095AED46AC1A523164E {
            get {
                return ResourceManager.GetString("XSD_61535827A4820095AED46AC1A523164E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;        ///
        ///&lt;xs:schema xmlns=&quot;http://xcri.org/profiles/catalog&quot; xmlns:x=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://xcri.org/profiles/catalog&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot;/&gt;        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/1999/xhtml&quot; schemaLocation=&quot;http://www.w3.org/2002/08/xhtml/xh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_65A805B501196FED109B22C8901DC333 {
            get {
                return ResourceManager.GetString("XSD_65A805B501196FED109B22C8901DC333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;!DOCTYPE xs:schema PUBLIC &quot;-//W3C//DTD XMLSCHEMA 200102//EN&quot; &quot;XMLSchema.dtd&quot; &gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xml:lang=&quot;en&quot;&gt;
        ///
        /// &lt;xs:annotation&gt;
        ///  &lt;xs:documentation&gt;
        ///   See http://www.w3.org/XML/1998/namespace.html and
        ///   http://www.w3.org/TR/REC-xml for information about this namespace.
        ///
        ///    This schema document describes the XML namespace, in a form
        ///    suitable for import by other schema document [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_712FC5A7750E69F904F61086A997713C {
            get {
                return ResourceManager.GetString("XSD_712FC5A7750E69F904F61086A997713C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///           xmlns:dcmitype=&quot;http://purl.org/dc/dcmitype/&quot;
        ///           targetNamespace=&quot;http://purl.org/dc/terms/&quot;
        ///           xmlns=&quot;http://purl.org/dc/terms/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      DCterms XML Schema
        ///      XML Schema for htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_72B0453C0918CCF69A5458231F389A3A {
            get {
                return ResourceManager.GetString("XSD_72B0453C0918CCF69A5458231F389A3A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///           xmlns:dcmitype=&quot;http://purl.org/dc/dcmitype/&quot;
        ///           targetNamespace=&quot;http://purl.org/dc/terms/&quot;
        ///           xmlns=&quot;http://purl.org/dc/terms/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      DCterms XML Schema
        ///      XML Schema for htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_78580479AA3D54F1558580380111F472 {
            get {
                return ResourceManager.GetString("XSD_78580479AA3D54F1558580380111F472", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema 
        ///
        /// xmlns=&quot;http://purl.org/net/mlo&quot;
        /// xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        /// xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        /// xmlns:credit=&quot;http://purl.org/net/cm&quot;
        /// xmlns:xcri=&quot;http://xcri.org/profiles/1.2/catalog&quot;
        /// xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        /// xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        /// xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot;
        /// targetNamespace=&quot;http://purl.org/net/mlo&quot;
        ///
        /// elementFormDefault=&quot;qualified&quot;&gt;
        /// 	&lt;xs:annotation&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_7E4D197B85AA9BFC7BC5C6FA7C3A0296 {
            get {
                return ResourceManager.GetString("XSD_7E4D197B85AA9BFC7BC5C6FA7C3A0296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://purl.org/net/cm&quot;
        ///	xmlns:credit=&quot;http://purl.org/net/cm&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;annotation&gt;
        ///		&lt;documentation xml:lang=&quot;en&quot;&gt;
        ///			This is an unofficial schema for
        ///			the CEN Educational Credit Information Model (CWA 16077:2010)
        ///		&lt;/documentation&gt;
        ///	&lt;/annotation&gt;
        ///
        ///	&lt;complexType name=&quot;Credit&quot;&gt;
        ///		&lt;sequence&gt;
        ///			&lt;element ref=&quot;credit:scheme&quot; maxOccurs=&quot;1&quot; minOccurs=&quot;0&quot;/&gt;
        ///			&lt;element [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_7F22B92E7365B08186651DA363696CF3 {
            get {
                return ResourceManager.GetString("XSD_7F22B92E7365B08186651DA363696CF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema 
        /// xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;  
        /// xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot;
        /// xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        /// elementFormDefault=&quot;qualified&quot;&gt;
        /// 
        /// 	&lt;xs:import namespace=&quot;http://www.w3.org/1999/xhtml&quot;	schemaLocation=&quot;http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd&quot; /&gt;
        /// 	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot;/&gt;
        /// 	
        /// 	&lt;!-- This schema defines some comm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_9CE854016084667957D64E301E1F2A6D {
            get {
                return ResourceManager.GetString("XSD_9CE854016084667957D64E301E1F2A6D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://purl.org/dc/dcmitype/&quot;
        ///           targetNamespace=&quot;http://purl.org/dc/dcmitype/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      DCMI Type Vocabulary XML Schema
        ///      XML Schema for http://purl.org/dc/dcmitype/ namespace
        ///
        ///      Created 2008-02-11
        ///
        ///      Created by 
        ///
        ///      T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_AA1D081C8A9C4610E3FA4125D2CCF322 {
            get {
                return ResourceManager.GetString("XSD_AA1D081C8A9C4610E3FA4125D2CCF322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema version=&quot;1.0&quot; xml:lang=&quot;en&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    targetNamespace=&quot;http://www.w3.org/1999/xhtml&quot;
        ///    xmlns=&quot;http://www.w3.org/1999/xhtml&quot;
        ///    xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        ///    elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///    XHTML 1.0 (Second Edition) Strict in XML Schema
        ///
        ///    This is the same as HTML 4 Strict except for
        ///    changes due to the differences between XML a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_AFC7D3BFB655C10D7D6C0EBC0A03CE91 {
            get {
                return ResourceManager.GetString("XSD_AFC7D3BFB655C10D7D6C0EBC0A03CE91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///           targetNamespace=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;xs:include schemaLocation=&quot;types.xsd&quot;&gt;&lt;/xs:include&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      DCMES 1.1 XML Schema
        ///      XML Schema for http://purl.org/dc/elements/1.1/ namespace
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_B05030F912901DE106631B5721BB8C1C {
            get {
                return ResourceManager.GetString("XSD_B05030F912901DE106631B5721BB8C1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema 
        ///	xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:mlo=&quot;http://purl.org/net/mlo&quot; 
        ///	xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///	xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///	targetNamespace=&quot;http://xcri.org/profiles/1.2/catalog&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_D8C4680FC0DA129F99107F4570BEBC41 {
            get {
                return ResourceManager.GetString("XSD_D8C4680FC0DA129F99107F4570BEBC41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///           targetNamespace=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;xs:include schemaLocation=&quot;types.xsd&quot;&gt;&lt;/xs:include&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation xml:lang=&quot;en&quot;&gt;
        ///      DCMES 1.1 XML Schema
        ///      XML Schema for http://purl.org/dc/elements/1.1/ namespace
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_DCB672EE323A6F53C60966C166ED756E {
            get {
                return ResourceManager.GetString("XSD_DCB672EE323A6F53C60966C166ED756E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema 
        ///	xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:mlo=&quot;http://purl.org/net/mlo&quot; 
        ///	xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///	xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///	targetNamespace=&quot;http://xcri.org/profiles/1.2/catalog&quot; elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_E5FB2D385391BEBC1612A9B3363ADCB0 {
            get {
                return ResourceManager.GetString("XSD_E5FB2D385391BEBC1612A9B3363ADCB0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema  
        ///	xmlns=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; 
        ///xmlns:x=&quot;http://www.w3.org/1999/xhtml&quot; 
        ///xmlns:xcri=&quot;http://xcri.org/profiles/1.2/catalog&quot; 
        ///xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///targetNamespace=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; 
        ///elementFormDefault=&quot;qualified&quot; 
        ///attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///    &lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_EA1085BF59CA78B54146D4143810AB05 {
            get {
                return ResourceManager.GetString("XSD_EA1085BF59CA78B54146D4143810AB05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;        ///
        ///&lt;xs:schema id=&quot;geo&quot;        ///
        ///    targetNamespace=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;        ///
        ///    elementFormDefault=&quot;qualified&quot;        ///
        ///    xmlns=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;        ///
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;        ///
        ///&gt;        ///
        ///  &lt;xs:simpleType name=&quot;lat&quot;&gt;        ///
        ///    &lt;xs:restriction base=&quot;xs:string&quot;&gt;        ///
        ///      &lt;xs:pattern value=&quot;-?[0-9]{1,3}\.?[0-9]{0,15}&quot; /&gt;        ///
        ///    &lt;/xs:restriction&gt;        ///
        ///  &lt;/xs:simpleType&gt;        ///
        ///  &lt;xs:simpleType name=&quot;long&quot;&gt;        ///
        ///    &lt;xs:restriction base=&quot;xs:strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSD_F9D2645489083EDD8FBD40AD6F4A2879 {
            get {
                return ResourceManager.GetString("XSD_F9D2645489083EDD8FBD40AD6F4A2879", resourceCulture);
            }
        }
    }
}
