//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.IValidationService.Valid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentValidators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentValidators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.IValidationService.Valid.DocumentValidators", typeof(DocumentValidators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abstract139Characters {
            get {
                return ResourceManager.GetString("Abstract139Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abstract140Characters {
            get {
                return ResourceManager.GetString("Abstract140Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbstractWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("AbstractWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbstractWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("AbstractWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbstractWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("AbstractWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgeElementNotUsed {
            get {
                return ResourceManager.GetString("AgeElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgeElementValidValue {
            get {
                return ResourceManager.GetString("AgeElementValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllUrlElementsMustContainValidUrls {
            get {
                return ResourceManager.GetString("AllUrlElementsMustContainValidUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicationProcedureWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("ApplicationProcedureWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicationProcedureWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("ApplicationProcedureWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicationProcedureWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("ApplicationProcedureWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssessmentWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("AssessmentWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssessmentWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("AssessmentWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssessmentWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("AssessmentWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceModeNotUsed {
            get {
                return ResourceManager.GetString("AttendanceModeNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceModeUsed {
            get {
                return ResourceManager.GetString("AttendanceModeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendancePatternNotUsed {
            get {
                return ResourceManager.GetString("AttendancePatternNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendancePatternUsed {
            get {
                return ResourceManager.GetString("AttendancePatternUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContributorElementNotUsed {
            get {
                return ResourceManager.GetString("ContributorElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateElementNotUsed {
            get {
                return ResourceManager.GetString("DateElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("DescriptionWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("DescriptionWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("DescriptionWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentRoot_Valid {
            get {
                return ResourceManager.GetString("DocumentRoot_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DurationElementNotEmpty {
            get {
                return ResourceManager.GetString("DurationElementNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAddress_ValidEmail {
            get {
                return ResourceManager.GetString("EmailAddress_ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HasPartElementNotUsed {
            get {
                return ResourceManager.GetString("HasPartElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Identifier_WithoutXsiType_AbsoluteUri {
            get {
                return ResourceManager.GetString("Identifier_WithoutXsiType_AbsoluteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Identifier_WithoutXsiType_RelativeUri {
            get {
                return ResourceManager.GetString("Identifier_WithoutXsiType_RelativeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsPartOfElementNotUsed {
            get {
                return ResourceManager.GetString("IsPartOfElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_LanguageOfAssessment {
            get {
                return ResourceManager.GetString("Languages_LanguageOfAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_LanguageOfInstruction {
            get {
                return ResourceManager.GetString("Languages_LanguageOfInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_XmlLangAttribute {
            get {
                return ResourceManager.GetString("Languages_XmlLangAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LearningOutcomeWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("LearningOutcomeWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LearningOutcomeWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("LearningOutcomeWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LearningOutcomeWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("LearningOutcomeWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoPhoneNumberOrFaxNumber {
            get {
                return ResourceManager.GetString("NoPhoneNumberOrFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectiveWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("ObjectiveWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectiveWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("ObjectiveWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectiveWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("ObjectiveWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhoneNumberAndFaxNumber {
            get {
                return ResourceManager.GetString("PhoneNumberAndFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostcodeElementIncluded {
            get {
                return ResourceManager.GetString("PostcodeElementIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostcodeElementNotIncluded {
            get {
                return ResourceManager.GetString("PostcodeElementNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrerequisiteWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("PrerequisiteWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrerequisiteWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("PrerequisiteWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrerequisiteWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("PrerequisiteWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Qualification_TitleElementNotUsed {
            get {
                return ResourceManager.GetString("Qualification_TitleElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegulationsWithHrefAndBlankValue {
            get {
                return ResourceManager.GetString("RegulationsWithHrefAndBlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegulationsWithHrefAndSelfClosing {
            get {
                return ResourceManager.GetString("RegulationsWithHrefAndSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegulationsWithoutHrefWithContent {
            get {
                return ResourceManager.GetString("RegulationsWithoutHrefWithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        generated=&quot;2011-03-21T20:00:23Z&quot;
        ///		xmlns=&quot;http://xcri.org [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Root_CorrectElement_CorrectNamespace {
            get {
                return ResourceManager.GetString("Root_CorrectElement_CorrectNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;provider xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        generated=&quot;2011-03-21T20:00:23Z&quot;
        ///		xmlns=&quot;http://xcri.or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Root_CorrectElement_IncorrectNamespace {
            get {
                return ResourceManager.GetString("Root_CorrectElement_IncorrectNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;provider xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        generated=&quot;2011-03-21T20:00:23Z&quot;
        ///		xmlns=&quot;http://xcri.or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Root_IncorrectElement_CorrectNamespace {
            get {
                return ResourceManager.GetString("Root_IncorrectElement_CorrectNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StudyModeNotUsed {
            get {
                return ResourceManager.GetString("StudyModeNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StudyModeUsed {
            get {
                return ResourceManager.GetString("StudyModeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubjectElementNotEmpty {
            get {
                return ResourceManager.GetString("SubjectElementNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubjectElementNotUsed {
            get {
                return ResourceManager.GetString("SubjectElementNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UniqueValidator_ProviderAndCourseSame {
            get {
                return ResourceManager.GetString("UniqueValidator_ProviderAndCourseSame", resourceCulture);
            }
        }
    }
}
