//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.IValidationService.Valid.ElementValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Credits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Credits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.IValidationService.Valid.ElementValidation.Credits", typeof(Credits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;catalog xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot;
        ///	xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///	xmlns:credit=&quot;http://purl.org/net/cm&quot;
        ///&gt;
        ///  &lt;provider&gt;
        ///    &lt;course&gt;
        ///		&lt;mlo:credit&gt;
        ///		&lt;credit:level&gt;http://purl.org/net/cm/terms/ECTS#1&lt;/credit:level&gt;
        ///		&lt;/mlo:credit&gt;
        ///	&lt;/course&gt;
        ///  &lt;/provider&gt;
        ///&lt;/catalog&gt;.
        /// </summary>
        internal static string WithLevel {
            get {
                return ResourceManager.GetString("WithLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;catalog xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot;
        ///	xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///	xmlns:credit=&quot;http://purl.org/net/cm&quot;
        ///&gt;
        ///  &lt;provider&gt;
        ///    &lt;course&gt;
        ///		&lt;mlo:credit&gt;
        ///			&lt;credit:scheme&gt;http://purl.org/net/cm/terms/ECTS&lt;/credit:scheme&gt;
        ///		&lt;/mlo:credit&gt;
        ///	&lt;/course&gt;
        ///  &lt;/provider&gt;
        ///&lt;/catalog&gt;.
        /// </summary>
        internal static string WithScheme {
            get {
                return ResourceManager.GetString("WithScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;catalog xmlns=&quot;http://xcri.org/profiles/1.2/catalog&quot;
        ///	xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///	xmlns:credit=&quot;http://purl.org/net/cm&quot;
        ///&gt;
        ///  &lt;provider&gt;
        ///    &lt;course&gt;
        ///		&lt;mlo:credit&gt;
        ///			&lt;credit:value&gt;20&lt;/credit:value&gt;
        ///		&lt;/mlo:credit&gt;
        ///	&lt;/course&gt;
        ///  &lt;/provider&gt;
        ///&lt;/catalog&gt;.
        /// </summary>
        internal static string WithValue {
            get {
                return ResourceManager.GetString("WithValue", resourceCulture);
            }
        }
    }
}
