//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.IValidationService.Invalid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentValidators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentValidators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.IValidationService.Invalid.DocumentValidators", typeof(DocumentValidators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abstract141Characters {
            get {
                return ResourceManager.GetString("Abstract141Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllUrlElementsMustContainValidUrls {
            get {
                return ResourceManager.GetString("AllUrlElementsMustContainValidUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContributorElementUsed {
            get {
                return ResourceManager.GetString("ContributorElementUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateElementUsed {
            get {
                return ResourceManager.GetString("DateElementUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;course xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentRoot_CannotBeACourse {
            get {
                return ResourceManager.GetString("DocumentRoot_CannotBeACourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;provider xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentRoot_CannotBeAProvider {
            get {
                return ResourceManager.GetString("DocumentRoot_CannotBeAProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DurationElementEmpty {
            get {
                return ResourceManager.GetString("DurationElementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DurationElementSelfClosing {
            get {
                return ResourceManager.GetString("DurationElementSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAddress_MissingDomain {
            get {
                return ResourceManager.GetString("EmailAddress_MissingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAddress_NoAt {
            get {
                return ResourceManager.GetString("EmailAddress_NoAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HasPartElementUsed {
            get {
                return ResourceManager.GetString("HasPartElementUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Identifier_WithoutXsiType_NotAUri {
            get {
                return ResourceManager.GetString("Identifier_WithoutXsiType_NotAUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Identifier_WithoutXsiType_RelativeUri {
            get {
                return ResourceManager.GetString("Identifier_WithoutXsiType_RelativeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsPartOfElementUsed {
            get {
                return ResourceManager.GetString("IsPartOfElementUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Qualification_TitleElementUsed {
            get {
                return ResourceManager.GetString("Qualification_TitleElementUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubjectElementEmpty {
            get {
                return ResourceManager.GetString("SubjectElementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubjectElementSelfClosing {
            get {
                return ResourceManager.GetString("SubjectElementSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubjectElementUsed {
            get {
                return ResourceManager.GetString("SubjectElementUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UniqueValidator_CourseNodes {
            get {
                return ResourceManager.GetString("UniqueValidator_CourseNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;catalog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///         xmlns:ukrlp=&quot;http://www.ukrlp.co.uk&quot;
        ///         xmlns:geo=&quot;http://www.w3.org/2003/01/geo/wgs84_pos&quot;
        ///         xmlns:xcri12terms=&quot;http://xcri.org/profiles/1.2/catalog/terms&quot; xmlns:mlo=&quot;http://purl.org/net/mlo&quot;
        ///         xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///         xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot;
        ///        xsi:schemaLocation=&quot;http://xcri.org/profiles/1.2/catalog h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UniqueValidator_ProviderNodes {
            get {
                return ResourceManager.GetString("UniqueValidator_ProviderNodes", resourceCulture);
            }
        }
    }
}
