//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Resources.ContentValidation.StringLengthValidator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Valid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Valid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Resources.ContentValidation.StringLengthValidator.Valid", typeof(Valid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;
        ///  &lt;dc:description href=&quot;http://hello.world.com&quot; /&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string DescriptionsWithHrefMustNotContainContent {
            get {
                return ResourceManager.GetString("DescriptionsWithHrefMustNotContainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;
        ///  &lt;dc:description&gt;Some content&lt;/dc:description&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string DescriptionsWithoutHrefMustContainContent {
            get {
                return ResourceManager.GetString("DescriptionsWithoutHrefMustContainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:xhtml=&quot;http://www.w3.org/1999/xhtml&quot;        ///&gt;
        ///  &lt;dc:description&gt;&lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;Some content in a div!&lt;/div&gt;&lt;/dc:description&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string DescriptionsWithoutHrefMustContainContent_HTML {
            get {
                return ResourceManager.GetString("DescriptionsWithoutHrefMustContainContent_HTML", resourceCulture);
            }
        }
    }
}
